version: "3.9"
name: oracle-xe-21c
services:
  oracle:
    image: gvenzl/oracle-xe:21-slim
    container_name: oracle-xe
    restart: unless-stopped
    environment:
      ORACLE_PASSWORD: oracle      # SYS、SYSTEM 默认密码
      APP_USER: appuser            # 业务用户（可选）
      APP_USER_PASSWORD: apppass   # 业务用户密码
      ORACLE_DATABASE: XE          # 默认库名
    ports:
      - "1521:1521"   # Oracle 服务端口
      - "5500:5500"   # 企业管理 EM Express（部分镜像可用）
    volumes:
      - oracle_data:/opt/oracle/oradata   # 持久化数据

volumes:
  oracle_data:
